### ISSUE TITLE
mount .x11-tmp as volume and render natively through x11

### ISSUE THREAD

**Issue by varung** [thewtex/docker-opengl#18]
Is it possible to instead of using the html5 renderer, directly render by mounting the x11 socket into the container?  I also do not mind running this with nvidia-docker if that will make this work.

**Comment by thewtex** [comment]
Yes, you can do something like that with `nvidia-docker` or these images, which were developed before `nvidia-docker` came out:

  https://github.com/thewtex/docker-opengl-nvidia
  https://github.com/thewtex/docker-opengl-mesa

See `run.sh` in particular.

However, this image is intended to work independent of the host OS (Windows, macOS, too), or host hardware or software drivers.
